# Generated by Django 5.1.11 on 2025-08-11 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visit',
            new_name='PageVisit',
        ),
    ]
